version: "3.9"
services:
  app:
    container_name: fisiocefan_app
    restart: always
    build: .
    ports:
      - "8080:80"
    volumes:
      - ".:/var/www/html"
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      PHP_ENV: 'DEVELOPMENT'
  db:
    container_name: fisiocefan_db
    image: mariadb:10.9.4
    restart: always
    ports:
      - "33306:3306"
    volumes:
      - "./static/db:/docker-entrypoint-initdb.d"
      - "./data:/var/lib/mysql"
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASS}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
  pma:
    image: phpmyadmin:5.2-fpm-alpine
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASS}
      PMA_HOST: 'db'
      PMA_PORT: 3306
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}